### PR TITLE
incremental scan: build delete index. only load from main & original; incremental indexing;

### PR DESCRIPTION
**Pull request by yatli**
~~this is a wip at the moment, as the indexer is not updated.~~

I've also updated the indexer so that it sends {main,original} or {main} to ES, decided by the `--incremental=...` flag.

Implements #225, #226

### CODE REVIEW

**Comment by yatli** [comment]
A //TODO stub is left out in elastic.c for bulk entry removal. @simon987 need your help.

**Comment by yatli** [comment]
ok other than the missing es bulk delete I think it's ready for review.

**Comment by yatli** [comment]
okay, bulk delete is implemented.
*not tested at all*

will try to mess with it once my scanning is done :)

**Comment by yatli** [comment]
tested, nothing blows up.
indexing is much faster than before, as expected.

**Comment by yatli** [comment]
emmm.. `sist2 web` only shows incremental changes now

**Comment by yatli** [comment]
ugh. my `_index_delete.list.zst` is 80M, unpacks to 144M.
150830889 / 33 = 4570633

Guess that's the total number of my files lol

**Comment by yatli** [comment]
there must be something that I've done wrong... (turning head to @simon987 )

**Comment by yatli** [comment]
Strange. Original table TN = 6M+, copy table TN = 2M+, but the new _index_original.ndjson will still contain 6M+ entries.

Are the entries from archives also copied over?
If so, I may have deleted all entries with a parent in ES.

**Comment by yatli** [comment]
When copy_table is far greater than new_table, we could as well first file copy the store and then remove entries from it.

**Comment by yatli** [comment]
036b03b fixes full scan regression (spamming hash table != NULL assertion failures)

**Comment by yatli** [comment]
Rebased to latest dev

**Comment by simon987** [comment]
sist2 incremental

I'm doing a diagram because it's getting a bit complicated, can you confirm that this is how the incremental feature works with this PR? I didn't draw the thumbnails store because, from what I understand, all items that are in the `original` index are copied to the thumbs store

**Comment by yatli** [comment]
Great drawing, and I think it captures the idea of this PR very well.

**Comment by simon987** [comment]
Thanks a lot @yatli ! Seems to work well so far

**Pull request merged**
